baseurl = "/"
title = "Mecklenburgischer Yachtclub Rostock"
languageCode = "de"
DefaultContentLanguage = "de"
paginate = "10" # Number of posts per page
theme = "hugo-dpsg"
pluralizeListTitles = "false"


[Author] # Used in authorbox
name = "Jan Beu"
bio = "Vorstandvorsitzender"
avatar = "img/avatar.png"

[Params.logo]
image = "img/MYCR-Stander-wehend-100.png" # Logo image. Path relative to "static"
header = "img/rostock_header.png" # Header image. Path relative to "static"
title = "Mecklenburgischer Yachtclub Rostock" # Logo title, otherwise will use site title
subtitle = "Seit 1884 · Uferpromenade 5a · 18147 Rostock" # Logo subtitle

[Params.style.vars]
highlightColor = "#2268ba" # Override main theme color

[Params.footer]
text = "[Impressum](/imprint)" # Extra text in footer row, understands markdown

[Params.sidebar]
home = "right" # Configure layout for home page
list = "right"  # Configure layout for list pages
single = false # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "recent_photos", "categories", "taglist", "social", "languages"]
# alternatively "ddg-search" can be used, to search via DuckDuckGo
# widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]



[Params]

#  description = "Welcome to our scout group!" # Site description. Used in meta description
#  copyright = "DGSP local group" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
#  schema = true # Enable Schema
#  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
#  authorbox = true # Show authorbox at bottom of pages if true
#  toc = false # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  indexPager = false # Show pager navigation on index page
#  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["Neuigkeiten", "Termine", "Verein"] # Specify section pages to show on home page and the "Recent articles" widget
#  photosSections = ["photos"] # Specify section pages to show on home page and the "Recent photos" widget
  dateformat = "02.01.2006" # Change the format of dates
#  customCSS = ["css/custom.css"] # Include custom CSS files
#  customJS = ["js/custom.js"] # Include custom JS files
#  customPartial = "piwik.html" # Include custom partials, e.g. tracking codes
